[metadata]
name = paw_statistics
version = 1.0.0
description = Paw keypoint segmentation and analysis tools
long_description = file: README.md
long_description_content_type = text/markdown
author = Christian Pritz
license = MIT
home_page = https://github.com/ChristianPritz/paw_statistics

[options]
packages =
    paw_statistics
package_dir =
    paw_statistics = code
include_package_data = True
python_requires = >=3.8
install_requires =
    numpy
    pandas
    scipy
    matplotlib
    scikit-learn
    pycircstat2
    opencv-python-headless

[options.package_data]
paw_statistics =
    *.json

[options.extras_require]
dev =
    pytest
    black
    flake8
    statsmodels
